USE bookstore;

INSERT INTO Book(title,genre,pubYear,readingLevel,isFeatured,collectionTag,coverImageUrl,isPremium,bookDescription,createdAt,updatedAt,AuthorId)
VALUES
('Parable of the Sower','Speculative Fiction',1993,'adult',1,'Future Visions','https://images.penguinrandomhouse.com/cover/9781538732182',1,'A prophetic coming-of-age story set in a climate ravaged America where empathy becomes a superpower.',sysdate(),sysdate(),1),
('The Left Hand of Darkness','Science Fiction',1969,'adult',1,'Future Visions','https://images.macmillan.com/folio-assets/cover-images/9780441478125.jpg',1,'An envoy to the icy planet Gethen uncovers a society without fixed genders and a conspiracy that could tear worlds apart.',sysdate(),sysdate(),2),
('The Ocean at the End of the Lane','Fantasy',2013,'general',1,'Wonder Tales','https://images.harpercollins.com/covers/9780062255679/y648.jpg',0,'Returning home for a funeral, a man recalls childhood memories tinged with myth and the uncanny.',sysdate(),sysdate(),3),
('Circe','Myth Retelling',2018,'general',0,'Mythic Women','https://images.macmillan.com/folio-assets/cover-images/9780316556323.jpg',0,'The witch of Aiaia steps into the spotlight in this lyrical retelling that follows centuries of self-discovery.',sysdate(),sysdate(),4),
('Song of Solomon','Literary Fiction',1977,'adult',0,'Legacy Lines','https://images.penguinrandomhouse.com/cover/9781400033416',1,'A sweeping exploration of family, flight, and the power of names within Black American history.',sysdate(),sysdate(),5),
('The Fifth Season','Science Fantasy',2015,'adult',1,'Worldbreakers','https://images.macmillan.com/folio-assets/cover-images/9780316229296.jpg',1,'As the world ends for the last time, an orogene fights to protect her daughter and unravel systemic oppression.',sysdate(),sysdate(),6),
('The Hate U Give','Young Adult',2017,'teen',0,'Voices Raised','https://images.harpercollins.com/covers/9780062498533/y648.jpg',0,'A teenager witnesses the police shooting of her best friend and becomes the face of a protest movement.',sysdate(),sysdate(),7),
('The Name of the Wind','Epic Fantasy',2007,'adult',0,'Worldbreakers','https://images.penguinrandomhouse.com/cover/9780756404741',1,'Kvothe recounts his legendary rise from gifted child to notorious magician.',sysdate(),sysdate(),8),
('Atomic Habits','Personal Development',2018,'general',0,'Momentum Makers','https://images.penguinrandomhouse.com/cover/9780735211292',0,'A framework for building better habits through small, consistent changes.',sysdate(),sysdate(),9),
('Little Fires Everywhere','Literary Fiction',2017,'general',1,'Community Curations','https://images.penguinrandomhouse.com/cover/9780735224315',0,'Secrets ignite tensions when a nomadic artist and her daughter settle in suburban Shaker Heights.',sysdate(),sysdate(),10);
